# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cgetPaths <- function(filepath) {
    .Call(`_pGMCM_cgetPaths`, filepath)
}

crowMatch <- function(assoc, nonconsec) {
    .Call(`_pGMCM_crowMatch`, assoc, nonconsec)
}

get_list_names <- function(L) {
    .Call(`_pGMCM_get_list_names`, L)
}

cpaste0 <- function(str1) {
    .Call(`_pGMCM_cpaste0`, str1)
}

cstr_split <- function(strings, split) {
    .Call(`_pGMCM_cstr_split`, strings, split)
}

trans_func <- function(x) {
    .Call(`_pGMCM_trans_func`, x)
}

caccept <- function(x, y) {
    .Call(`_pGMCM_caccept`, x, y)
}

cget_prior_count <- function(red_class, mus, labels, d, n, dist_tol = 0L) {
    .Call(`_pGMCM_cget_prior_count`, red_class, mus, labels, d, n, dist_tol)
}

cget_true_assoc_idx <- function(red_class, true_assoc) {
    .Call(`_pGMCM_cget_true_assoc_idx`, red_class, true_assoc)
}

cassociate <- function(paths, filepath, len_filt_h) {
    .Call(`_pGMCM_cassociate`, paths, filepath, len_filt_h)
}

abs3 <- function(val) {
    .Call(`_pGMCM_abs3`, val)
}

SCAD_1d <- function(prop, lambda, k, a = 3.7) {
    .Call(`_pGMCM_SCAD_1d`, prop, lambda, k, a)
}

double_SCAD_1d <- function(prop, lambda, a = 3.7) {
    .Call(`_pGMCM_double_SCAD_1d`, prop, lambda, a)
}

SCAD <- function(prop, lambda, k, a = 3.7) {
    .Call(`_pGMCM_SCAD`, prop, lambda, k, a)
}

double_SCAD <- function(prop, lambda, a = 3.7) {
    .Call(`_pGMCM_double_SCAD`, prop, lambda, a)
}

choose_slice <- function(Q, idx, d, k) {
    .Call(`_pGMCM_choose_slice`, Q, idx, d, k)
}

Mahalanobis <- function(x, mu, sigma) {
    .Call(`_pGMCM_Mahalanobis`, x, mu, sigma)
}

cdmvnorm <- function(x, mu, sigma) {
    .Call(`_pGMCM_cdmvnorm`, x, mu, sigma)
}

cfpGMM <- function(x, prop, mu, sigma, k, df, lambda, citermax, tol) {
    .Call(`_pGMCM_cfpGMM`, x, prop, mu, sigma, k, df, lambda, citermax, tol)
}

cget_constr_sigma <- function(sigma, rho, combos, d) {
    .Call(`_pGMCM_cget_constr_sigma`, sigma, rho, combos, d)
}

trans_rho <- function(rho) {
    .Call(`_pGMCM_trans_rho`, rho)
}

trans_rho_inv <- function(rho) {
    .Call(`_pGMCM_trans_rho_inv`, rho)
}

func_to_optim <- function(init_val, x, h_est, combos) {
    .Call(`_pGMCM_func_to_optim`, init_val, x, h_est, combos)
}

optim_rcpp <- function(init_val, x, h_est, combos) {
    .Call(`_pGMCM_optim_rcpp`, init_val, x, h_est, combos)
}

cfconstr_pGMM <- function(x, prop, mu, sigma, rho, combos, k, df, lambda, citermax, tol, LASSO) {
    .Call(`_pGMCM_cfconstr_pGMM`, x, prop, mu, sigma, rho, combos, k, df, lambda, citermax, tol, LASSO)
}

bind_diags <- function(Sigma_in) {
    .Call(`_pGMCM_bind_diags`, Sigma_in)
}

bind_offdiags <- function(Sigma_in) {
    .Call(`_pGMCM_bind_offdiags`, Sigma_in)
}

get_sigma_optim <- function(diagbind, combos) {
    .Call(`_pGMCM_get_sigma_optim`, diagbind, combos)
}

get_mu_optim <- function(mu_in, combos) {
    .Call(`_pGMCM_get_mu_optim`, mu_in, combos)
}

get_rho_optim <- function(rhobind, combos) {
    .Call(`_pGMCM_get_rho_optim`, rhobind, combos)
}

func_to_optim0 <- function(init_val, x, h_est, combos, a, b, c, negidx) {
    .Call(`_pGMCM_func_to_optim0`, init_val, x, h_est, combos, a, b, c, negidx)
}

optim0_rcpp <- function(init_val, x, h_est, combos, a, b, c, negidx) {
    .Call(`_pGMCM_optim0_rcpp`, init_val, x, h_est, combos, a, b, c, negidx)
}

cfconstr0_pGMM <- function(x, prop, mu, Sigma, combos, k, df, lambda, citermax, tol) {
    .Call(`_pGMCM_cfconstr0_pGMM`, x, prop, mu, Sigma, combos, k, df, lambda, citermax, tol)
}

cduvnorm <- function(x, mu, sigma) {
    .Call(`_pGMCM_cduvnorm`, x, mu, sigma)
}

cmarg_ll_gmm <- function(z, mu, sigma, prop, combos, k) {
    .Call(`_pGMCM_cmarg_ll_gmm`, z, mu, sigma, prop, combos, k)
}

cll_gmm <- function(z, mu, sigma, rho, prop, combos, k) {
    .Call(`_pGMCM_cll_gmm`, z, mu, sigma, rho, prop, combos, k)
}

cmarg0_ll_gmm <- function(z, mu, Sigma, prop, k) {
    .Call(`_pGMCM_cmarg0_ll_gmm`, z, mu, Sigma, prop, k)
}

cll0_gmm <- function(z, mu, Sigma, prop, k) {
    .Call(`_pGMCM_cll0_gmm`, z, mu, Sigma, prop, k)
}

