# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

choose_slice <- function(Q, idx, d, k) {
    .Call(`_pGMCM_choose_slice`, Q, idx, d, k)
}

Mahalanobis <- function(x, mu, sigma) {
    .Call(`_pGMCM_Mahalanobis`, x, mu, sigma)
}

cdmvnorm <- function(x, mu, sigma) {
    .Call(`_pGMCM_cdmvnorm`, x, mu, sigma)
}

cfpGMM <- function(x, prop, mu, sigma, k, df, lambda, citermax, tol) {
    .Call(`_pGMCM_cfpGMM`, x, prop, mu, sigma, k, df, lambda, citermax, tol)
}

abs3 <- function(val) {
    .Call(`_pGMCM_abs3`, val)
}

cget_constr_sigma <- function(sigma, rho, combos, d) {
    .Call(`_pGMCM_cget_constr_sigma`, sigma, rho, combos, d)
}

trans_rho <- function(rho) {
    .Call(`_pGMCM_trans_rho`, rho)
}

trans_rho_inv <- function(rho) {
    .Call(`_pGMCM_trans_rho_inv`, rho)
}

func_to_optim <- function(init_val, x, h_est, combos) {
    .Call(`_pGMCM_func_to_optim`, init_val, x, h_est, combos)
}

optim_rcpp <- function(init_val, x, h_est, combos) {
    .Call(`_pGMCM_optim_rcpp`, init_val, x, h_est, combos)
}

cfconstr_pGMM <- function(x, prop, mu, sigma, rho, combos, k, df, lambda, citermax, tol) {
    .Call(`_pGMCM_cfconstr_pGMM`, x, prop, mu, sigma, rho, combos, k, df, lambda, citermax, tol)
}

bind_diags <- function(Sigma_in) {
    .Call(`_pGMCM_bind_diags`, Sigma_in)
}

bind_offdiags <- function(Sigma_in) {
    .Call(`_pGMCM_bind_offdiags`, Sigma_in)
}

get_sigma_optim <- function(diagbind, combos) {
    .Call(`_pGMCM_get_sigma_optim`, diagbind, combos)
}

get_mu_optim <- function(mu_in, combos) {
    .Call(`_pGMCM_get_mu_optim`, mu_in, combos)
}

get_rho_optim <- function(rhobind, combos) {
    .Call(`_pGMCM_get_rho_optim`, rhobind, combos)
}

func_to_optim0 <- function(init_val, x, h_est, combos, a, b, c, negidx) {
    .Call(`_pGMCM_func_to_optim0`, init_val, x, h_est, combos, a, b, c, negidx)
}

optim0_rcpp <- function(init_val, x, h_est, combos, a, b, c, negidx) {
    .Call(`_pGMCM_optim0_rcpp`, init_val, x, h_est, combos, a, b, c, negidx)
}

cfconstr0_pGMM <- function(x, prop, mu, Sigma, combos, k, df, lambda, citermax, tol) {
    .Call(`_pGMCM_cfconstr0_pGMM`, x, prop, mu, Sigma, combos, k, df, lambda, citermax, tol)
}

cduvnorm <- function(x, mu, sigma) {
    .Call(`_pGMCM_cduvnorm`, x, mu, sigma)
}

cmarg_ll_gmm <- function(z, mu, sigma, prop, combos, k) {
    .Call(`_pGMCM_cmarg_ll_gmm`, z, mu, sigma, prop, combos, k)
}

cll_gmm <- function(z, mu, sigma, rho, prop, combos, k) {
    .Call(`_pGMCM_cll_gmm`, z, mu, sigma, rho, prop, combos, k)
}

teststuff <- function(mu_old, Sigma_old, combos) {
    .Call(`_pGMCM_teststuff`, mu_old, Sigma_old, combos)
}

