# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

choose_slice <- function(Q, idx, d, k) {
    .Call(`_pGMCM_choose_slice`, Q, idx, d, k)
}

Mahalanobis <- function(x, mu, sigma) {
    .Call(`_pGMCM_Mahalanobis`, x, mu, sigma)
}

cdmvnorm <- function(x, mu, sigma) {
    .Call(`_pGMCM_cdmvnorm`, x, mu, sigma)
}

cfpGMM <- function(x, prop, mu, sigma, k, df, citermax, lambda) {
    .Call(`_pGMCM_cfpGMM`, x, prop, mu, sigma, k, df, citermax, lambda)
}

