# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

choose_slice <- function(Q, idx, d, k) {
    .Call(`_pGMCM_choose_slice`, Q, idx, d, k)
}

Mahalanobis <- function(x, mu, sigma) {
    .Call(`_pGMCM_Mahalanobis`, x, mu, sigma)
}

cdmvnorm <- function(x, mu, sigma) {
    .Call(`_pGMCM_cdmvnorm`, x, mu, sigma)
}

cfpGMM <- function(x, prop, mu, sigma, k, df, citermax, lambda) {
    .Call(`_pGMCM_cfpGMM`, x, prop, mu, sigma, k, df, citermax, lambda)
}

C_fpGMM <- function(sigma) {
    .Call(`_pGMCM_C_fpGMM`, sigma)
}

C_oneL <- function(prob0) {
    .Call(`_pGMCM_C_oneL`, prob0)
}

C_slice <- function(n, d, k, x, mu_new, h_est, sigma_old) {
    .Call(`_pGMCM_C_slice`, n, d, k, x, mu_new, h_est, sigma_old)
}

choose_list <- function(sigma, idx) {
    .Call(`_pGMCM_choose_list`, sigma, idx)
}

getuvec <- function(input, sigma) {
    .Call(`_pGMCM_getuvec`, input, sigma)
}

